### ISSUE TITLE
Add rent stabilization data scraped from 2019 tax bills

### ISSUE THREAD

**Issue by toolness** [nycdb/nycdb#121]
We've recently completed a download of all 2019 Statement of Account (SOA) tax bill data that corresponds to BBLs stored in PLUTO 19_v1.  We also converted the PDFs to text and attempted to parse out information about how many rent-stabilized units are mentioned in each BBL's tax bill (if any).

The result is a dataset that is different from the existing rent stabilization data in a number of ways:

* We *only* pulled the rent stabilization numbers from the tax bills.  We didn't scrape anything about J-51 and other tax abatements because the most important ones have recently been added to NYC's open data portal and brought into NYCDB by PRs like [#80](https://github.com/nycdb/nycdb/pull/80).  (If there is strong interest in obtaining other numbers from the PDFs, we can always add them later.)

* We are applying as little post-processing to the data as possible, as interviews with users of the existing stabilization data have expressed confusion and distrust of the numbers in it.  In line with this, we also would like to provide direct links to the PDFs of the tax bills that the data was scraped from.  This allows anyone to easily trace the data provenance of every statistic if they have any doubts about the accuracy of the scrape.

Given this, we're proposing a new dataset with the following structure:

| BBL        | soa_downloaded | soa_rentstab_units           | soa_url |
| ------------- |:-------------:| -----:| -----:|
| 1011587504     | t | 31 | https://nyc-doffer.s3.amazonaws.com/pdf/1/01158/7504/soa-2019-06-05.pdf.br |

* **BBL** (10-character string) is the Boro-Block-Lot number of the property.
* **soa_downloaded** (boolean) represents whether or not we were able to download the SOA from the DOF site.  (The DOF site reported that it didn't have SOAs for a few hundred of the BBLs in question.)
* **soa_rentstab_units** (null or positive integer) is the 2018 rent stabilization count, as extracted from the 2019 SOA.  If it is null, then we were not able to find any mention of a rent stabilization count (this could mean the building has no rent stabilized units, but it could also mean that our scraping logic couldn't find the mention, or it could mean that for some reason the building wasn't charged a rent stabilization fee that year for some reason).
* **soa_url** (string) is the URL to the PDF of the 2019 SOA that we downloaded from the DOF site. Curious users can refer to this if they doubt the accuracy of our scrape.

**Comment by toolness** [comment]
Hi @aepyornis, any thoughts on this?  No worries if you're too busy...

**Comment by sraby** [comment]
Also, @0xStarcat what are your thoughts on this? I imagine y'all will want to use this new data in DAP Portal

**Comment by aepyornis** [comment]
@toolness Sounds interesting. Do you have a link to the code that does the downloading/parsing of the SOA data?

**Comment by toolness** [comment]
Oh sure it is here: https://github.com/justfixnyc/nyc-doffer

It started out as a weird weekend experiment but then it started growing. 😳

**Comment by aepyornis** [comment]
Cool. Instead of it being 2018 specific, does it make more sense for it to have a year field as well?  That way in the future if you scrape to get 2019 (or 2017's) we don't have to change around the fields or documentation as much?

**Comment by aepyornis** [comment]
Also one more question -- what's with the br on the end of the pdfs?

**Comment by lblok** [comment]
This looks good to me! I agree about adding a year field (ziggy do you mean like calling it uc2018?)

**Comment by toolness** [comment]
> Instead of it being 2018 specific, does it make more sense to also add a year field as well? That way in the future if you scrape to get 2019 (or 2017's) we don't have to change around the fields or documentation as much?

Oh interesting, so you mean just adding another "year" field so the example row would look like this?

| year | BBL        | soa_downloaded | soa_rentstab_units           | soa_url |
| ---- | ------------- |:-------------:| -----:| -----:|
| 2018 | 1011587504     | t | 31 | https://nyc-doffer.s3.amazonaws.com/pdf/1/01158/7504/soa-2019-06-05.pdf.br |

> Also one more question -- what's with the br on the end of the pdfs?

I've actually Brotli-compressed the PDFs, to save a tiny bit on storage/transmission costs.  Ideally the extension would be `.br.pdf` rather than `.pdf.br` but, err, it's a long story.

**Comment by austensen** [comment]
This all looks good to me. Thanks for all the work putting this together! 
I agree that adding the year like you have here is useful. We should make sure to be clear in the documentation about what the "year" reflects (since I believe the numbers in the tax bills reflects the units registered in the previous year, right?)

**Comment by toolness** [comment]
Yup, totally--in fact I keep stumbling when mentioning the year because it's the 2019 tax bills, but they describe the rent stabilized landscape of 2018... oy.  Thanks for bringing that up!

**Comment by aepyornis** [comment]
Sounds good. I understand the desire to save hosting costs, but because non-coders end up using our datasets, I think it would be easier to use regular .pdf links to avoid problems and confusion for others.

**Comment by toolness** [comment]
Um, changing that at this point would be very hard.  I don't think I can manage that, sorry.

**Comment by toolness** [comment]
I should add that actually linking to the PDF was an idea I thought of at the last minute, as something that would aid folks who were skeptical about the source of the data.  It was originally an implementation detail--the original rentstab data didn't include such a thing--and at this point it's so baked-in to the whole data pipeline that it'd be difficult to change.  I also don't think I can change it going forward for the sake of keeping the URL structure consistent.

Trust me, I originally tried saving this as a `.br.pdf` but stupid things got in the way.  I really don't think I can make this change, can we just move forward with making this a dataset?

**Comment by toolness** [comment]
Er, lastly, I should note that the actual _viewing_ of the PDF is fine in modern browsers: as clicking on that link in the example should attest, the `.pdf.br`'s are being sent with a `Content-Encoding: br` header, so it's not like users will have to manually decompress them like they would if they were ZIP files.  Saving them from their browser will be a bit weird because the browser will likely give the file an additional `.pdf` extension, resulting in a final `.pdf.br.pdf` extension, which is inconvenient and a bit confusing but not a dealbreaker in my opinion.

**Comment by austensen** [comment]
I agree that it doesn't seem like that big of a deal. I'm sure most people would just be opening it up in the browser for a quick check anyway and that works just fine. It's amazing just to have these all archived this way.

**Comment by aepyornis** [comment]
Yeah it's a little weird how that all works right now. Firefox  does render the pdf correctly with the extension .pdf.br, but if save the file from firefox it saves a file as a pdf without compression with an incorrect extension `.pdf.br`. My PDF reader doesn't recognize the file unless I rename it. If use curl to download the same file if it saves it with the same extension `.pdf.br` but it remains compressed.

I don't understand S3 all that well, but if it's a linux box this should do it ` find . -name '*.pdf.br' | xargs -L 1 brotli --decompress ` 

I agree, it's not a deal-breaker or anything , so if it can't be changed of course it's fine. Thank for for providing the PDFs!

FYI, the original tax bills dataset did include the html and text files derived from the pdfs. Example: http://taxbills.nyc/3/00062/0001/

**Comment by lblok** [comment]
I also agree that it doesn't seem like a big deal if it's a heavy lift to change it, but I don't understand the technical work involved.
