### ISSUE TITLE
The PAD dataset can no longer be downloaded

### ISSUE THREAD

**Issue by toolness** [nycdb/nycdb#135]
The download URL for the pad dataset, specified here, appears to 404 now:

https://github.com/nycdb/nycdb/blob/ada7c041a5bf6ba32832e6cf62a0fd66e1a3ccce/src/nycdb/datasets/pad.yml#L4

According to @sraby, it looks like PAD updates similarly to PLUTO where they release new versions accessible at new urls: 

https://www1.nyc.gov/site/planning/data-maps/open-data/bytes-archive.page?sorts[year]=0

So I guess we need to make sure that URL is always up-to-date?

**Comment by toolness** [comment]
I think that [NYC Planning Labs GeoSearch](https://github.com/NYCPlanning/labs-geosearch-docker) is somehow able to figure out what the latest PAD URL is, so that might be a place to look for fixing this.  (That said, it might involve making the download link _dynamic_ instead of statically specified in a YAML file.)

**Comment by austensen** [comment]
I think they have fixed this - when I try to download the table via nycdb this is what I see:
```
INFO:root:Downloading https://data.cityofnewyork.us/download/bc8t-ecyu/application%2Fzip to /Users/maxwell/data/pad.zip
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): data.cityofnewyork.us:443
DEBUG:urllib3.connectionpool:https://data.cityofnewyork.us:443 "GET /download/bc8t-ecyu/application%2Fzip HTTP/1.1" 302 None
DEBUG:urllib3.connectionpool:https://data.cityofnewyork.us:443 "GET /api/views/bc8t-ecyu/files/d2a97637-c418-4557-9230-0f31136cc555?filename=pad20c.zip HTTP/1.1" 200 None
```

So it seems like now it is properly redirecting from the original open data link to the most recent version.
