### ISSUE TITLE
hpd_violations dataset crashes due to "rentimpairing" KeyError

### ISSUE THREAD

**Issue by toolness** [nycdb/nycdb#148]
For the past few days, the NYCDB auto-updater has been failing when processing the `hpd_violations` dataset with the following traceback:

> ![image](https://user-images.githubusercontent.com/124687/98540256-a7f2af00-225b-11eb-9414-3a7f9e438e0b.png)

So it looks like perhaps the "rentimpairing" column has been ~~removed from~~ added to this dataset?

**Comment by sraby** [comment]
@toolness I just checked and I think it's the other way around- `rentimpairing` is a _new_ column that was added to the [table on NYC Open Data](https://data.cityofnewyork.us/Housing-Development/Housing-Maintenance-Code-Violations/wvxf-dwi5) but is not yet reflected in our schema. I can fix this during the next few days.

**Comment by toolness** [comment]
Ohh right got it!  Awesome thanks!
