### ISSUE TITLE
Consider adding a "pluto_latest" dataset that contains the latest PLUTO data

### ISSUE THREAD

**Issue by toolness** [nycdb/nycdb#159]
Since new versions of PLUTO are coming out on a monthly basis, it might be useful to have a table called `pluto_latest` (or something similar) that just has the latest PLUTO data, perhaps constrained to a subset of columns that reliably exist across all versions of PLUTO and aren't likely to go away anytime soon.  This way, auto-updating NYCDB instances can be relied on to have the latest data regardless of whether someone has added the particular PLUTO dataset to NYCDB's codebase (although it would obviously prevent access to _historical_ versions of PLUTO).

The main caveat here is in regards to what expectations there are around the evolution of PLUTO's schema.  I [posted](https://mapplutonycplanning.slack.com/archives/CGP5P70LQ/p1615216991002100) the following in the MapPLUTO NYCPlanning slack:

> Hi all!  We are super excited that PLUTO is being updated so frequently now... one question we have @Amanda Doyle is, are there expectations we should have around the evolution of the schema?  for instance, now that PLUTO is being updated so frequently we'd like to just have a "latest PLUTO data" table in our database, but it would be unfortunate if suddenly a column we relied on disappeared one day or something.  Do you know how likely this might be?

However, I haven't gotten a reply back yet, and I posted that on March 8th...

**Comment by aepyornis** [comment]
Good idea! One way is to use a view  -- `CREATE VIEW pluto AS SELECT * FROM pluto_10v8` -- and then delete and update it whenever there is a new pluto version.
