### ISSUE TITLE
Just installed nycdb but commands not working

### ISSUE THREAD

**Issue by naticio** [nycdb/nycdb#191]
nycdb is installed but nycdb commands are not recognized. I'm not a python guy and this pip thing made me spend 3 hrs googling how to install it correctly, thanks!
![image](https://user-images.githubusercontent.com/34293050/173172046-5728ed7c-a8ed-48c7-92b7-32434b4f7818.png)

**Comment by naticio** [comment]
![image](https://user-images.githubusercontent.com/34293050/173268102-6f2243cd-4f33-4fe2-b904-d4b68e6c1d04.png)

**Comment by aepyornis** [comment]
Someone with more mac knowledge can hopefully chime in on why nycdb isn't added to your path after installing. However, you should be able to execute it like such: `python3 -m nycdb.cli --help`

**Comment by wstlabs** [comment]
Looks like a path issue - works for me using venv.
Recommend we close.
