### ISSUE TITLE
add PLUTO land use category descriptions

### ISSUE THREAD

**Issue by pspauster** [nycdb/nycdb#225]
`landuse` field in PLUTO is currently encoded with values 01-11. Create new field with the category name according to the PLUTO documentation

This can likely be done with a case when statement before the dataset uploaded to SQL DB

VALUE DESCRIPTION
01 One & Two Family Buildings
02 Multi-Family Walk-Up Buildings
03 Multi-Family Elevator Buildings
04 Mixed Residential & Commercial Buildings
05 Commercial & Office Buildings
06 Industrial & Manufacturing
07 Transportation & Utility
08 Public Facilities & Institutions
09 Open Space & Outdoor Recreation
10 Parking Facilities
11 Vacant Land

**Comment by austensen** [comment]
resolved in #226
