### ISSUE TITLE
pluto_latest is not up to date

### ISSUE THREAD

**Issue by lblok** [nycdb/nycdb#264]
NYC Open Data version is 23v1.1, pluto_latest is 22v2

**Comment by austensen** [comment]
This is primarily an issue with the scheduling in [JustFixNYC/nycdb-k8s-loader](https://github.com/JustFixNYC/nycdb-k8s-loader). It should check every other day, but it was mistakenly set to annual (like static pluto versions). I'll fix this. 

But I just triggered the job manually, and I'm getting an error that's likely related to a change in the dataset columns. Just made a new issue for this: #265

**Comment by lblok** [comment]
I saw what looked like some new columns, so it could be that
