### ISSUE TITLE
Encountered Key Error Loading Pluto_Latest

### ISSUE THREAD

**Issue by wvasquezz** [nycdb/nycdb#273]
Hello I hope all is well. The last two columns(bct2020 and bctcb2020) were truncated when I attempted to load the pluto_latest dataset. Resulting in a key error when inserting into the table. Not sure on the next step I should take. 
<img width="1274" alt="Screen Shot 2023-10-31 at 3 38 15 AM" src="https://github.com/nycdb/nycdb/assets/122462174/4aeb9da4-daa9-430b-90b5-2a85dfaed069">
<img width="981" alt="Screen Shot 2023-10-31 at 3 40 19 AM" src="https://github.com/nycdb/nycdb/assets/122462174/0493e607-47d5-4ab3-8eb9-e4062554aecc">

**Comment by austensen** [comment]
Hey @wvasquezz, thanks for pointing this out! Looks like they just reordered the columns on the ope data file. I've updated nycdb's layout to reflect the changes, and we'll get that fix merged in shortly
