### ISSUE TITLE
Add NYC Property Address Directory (PAD) as a dataset

### ISSUE THREAD

**Issue by toolness** [nycdb/nycdb#77]
The [NYC open data feed for PAD](https://data.cityofnewyork.us/City-Government/Property-Address-Directory/bc8t-ecyu) is useful because it essentially maps BINs to BBLs, which is very useful for cross-referencing different kinds of datasets.

It will also be useful in Who Owns What, so that we can let users know that the statistics they're seeing for a building might actually represent aggregate data amongst multiple buildings (e.g. if multiple BINs map to the same BBL).

**Comment by aepyornis** [comment]
I'm down to include PAD if it's useful for folks!! However, I am curious,  if you have an example query of how this can be used with the data already in NYCDB?  I can't recall, do we have a dataset that has only BIN and not BBL?

Pluto does, fyi, already have a field for number of buildings.

**Comment by aepyornis** [comment]
thanks for the info @sraby !
