### ISSUE TITLE
Consider removing "Future datasets to add" from README and instead add a new "dataset request" issue label

### ISSUE THREAD

**Issue by toolness** [nycdb/nycdb#84]
The README currently has a "Future datasets to add" section that contains one item, "census data".  To make things more participatory and encourage discussion, I'm wondering if it might be more useful to instead have a new GitHub issue label called "dataset request" (or something similar) and encourage folks to file issues with that label?  For examples of such issues, see #22, #24, #76, #77, and #78.

For more context: we'd like to have a NYC-DB hackathon soon, and as a lead-in to that, we want to encourage HDC members to file github issues for potential improvements to NYC-DB.  Adding new datasets seems like the kind of thing that it'd be useful to have a label for, especially since it makes it easy to see a list of all currently-requested new datasets.

**Comment by austensen** [comment]
This has all been done!
